name: "Render Markdown Templates"
description: "Rendert *.tpl.*.md mit {file:...} und {var:...}; {var:version} nur aus composer.json"
inputs:
  working-directory:
    description: "Arbeitsverzeichnis im aufrufenden Repo"
    default: "."
    required: false
  inputs:
    description: "Zeilenweise Globs/Dateien für Templates (z. B. docs/**/*.tpl.*.md)"
    default: |
      **/*.tpl.*.md
    required: false
  snippets-path:
    description: "Pfad zum Snippets-Ordner relativ zu dieser Action"
    default: "snippets"
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Python deps
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml

    - name: Render templates
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        # für {var:repo_name} & {var:branch_name}; {var:version} kommt aus composer.json
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
      run: |
        set -euo pipefail

        # Build args array aus zeilenweiser inputs-Liste
        mapfile -t _LINES < <(printf '%s\n' "${{ inputs.inputs }}")
        ARGS=()
        for line in "${_LINES[@]}"; do
          [[ -z "$line" ]] && continue
          ARGS+=( --inputs "$line" )
        done

        python "$GITHUB_ACTION_PATH/scripts/render_markdown_templates.py" \
          --snippets-dir "$GITHUB_ACTION_PATH/${{ inputs.snippets-path }}" \
          "${ARGS[@]}"
