name: Update docs
on:
  workflow_call:
    inputs:
      extensionName:
        required: true
        type: string

    secrets:
      docsToken:
        required: true

concurrency:
  group: docs-sync-global
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      SOURCE_DIR: docs
      TARGET_REPO: moori-net/MoorlDocs
      TARGET_BRANCH: master
      TARGET_PATH: docs-source/plugin/${{ inputs.extensionName }}

    steps:
      - name: Checkout source repo (A)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Render templates ({file:...}, {var:...})
        uses: moorl/github-actions/.github/actions/render-markdown@main
        with:
          working-directory: .
          inputs: |
            ${{
              env.SOURCE_DIR
            }}/**/*.tpl.md

      - name: Verify rendered docs
        run: |
          echo "PWD: $(pwd)"
          ls -laR "${SOURCE_DIR}" || true

      - name: Checkout target repo (B)
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TARGET_REPO }}
          token: ${{ secrets.docsToken }}
          path: target
          ref: ${{ env.TARGET_BRANCH }}
          fetch-depth: 0

      - name: Sync files into target path
        run: |
          set -e
          mkdir -p "target/${TARGET_PATH}"
          # Zielordner leeren (Repo-Metadaten behalten)
          rm -rf "target/${TARGET_PATH:?}/"* "target/${TARGET_PATH}"/.[!.]* "target/${TARGET_PATH}"/..?* || true
          # Nur die gerenderten Markdown-Dateien rüberkopieren (keine .tpl.md)
          rsync -a \
            --exclude='.git' \
            --exclude='*.tpl.md' \
            "${SOURCE_DIR}/" "target/${TARGET_PATH}/"

      - name: Commit & push if changes
        working-directory: target
        run: |
          set -e
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(sync): update ${TARGET_PATH} from ${GITHUB_REPOSITORY}@${GITHUB_SHA}"
            git push origin "${TARGET_BRANCH}"
            echo "Changes pushed."
          else
            echo "No changes to commit."
          fi
